#!/bin/bash

# download the FaceRecognition.zip file from dropbox
echo "Downloading FaceRecognition.zip"
wget -q -O ~/notebooks/FaceRecognition.zip "https://dl.dropboxusercontent.com/s/q030cu844joczm6/FaceRecognition.zip"
echo "Finished downloading FaceRecognition.zip"

echo "Unzipping FaceRecognition.zip"
unzip ~/notebooks/FaceRecognition.zip -d ~/notebooks/
echo "Finished unzipping FaceRecognition.zip"

echo "Removing FaceRecognition.zip"
rm ~/notebooks/FaceRecognition.zip
echo "Finished removing FaceRecognition.zip"

# move the contents from ~notebooks/FaceRecognition/data/bids to ~notebooks/data
echo "Moving the contents from ~notebooks/FaceRecognition/data/bids to ~notebooks/data"
mv ~/notebooks/FaceRecognition/data/bids/* ~/notebooks/data/
echo "Finished moving the contents from ~notebooks/FaceRecognition/data/bids to ~notebooks/data"